### ISSUE TITLE
Invalid value for `format`, must not be `None`

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/client-python#23] opened 2018-06-29 10:42 UTC
With the latest client downloaded few mins ago. When there is single `vmi` created using this [manifest](https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vmi-ephemeral.yaml). When calling `list_virtual_machine_instance_for_all_namespaces` I get:

```
  File "/usr/lib/python2.7/site-packages/kubevirt/apis/default_api.py", line 2884, in list_virtual_machine_instance_for_all_namespaces
    (data) = self.list_virtual_machine_instance_for_all_namespaces_with_http_info(**kwargs)
  File "/usr/lib/python2.7/site-packages/kubevirt/apis/default_api.py", line 2978, in list_virtual_machine_instance_for_all_namespaces_with_http_info
    collection_formats=collection_formats)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 326, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 161, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 239, in deserialize
    return self.__deserialize(data, response_type)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 279, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 629, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 257, in __deserialize
    for sub_data in data]
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 279, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 629, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 279, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 629, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 279, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 629, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 279, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 629, in __deserialize_model
    kwargs[attr] = self.__deserialize(value, attr_type)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 262, in __deserialize
    for k, v in iteritems(data)}
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 262, in <dictcomp>
    for k, v in iteritems(data)}
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 279, in __deserialize
    return self.__deserialize_model(data, klass)
  File "/usr/lib/python2.7/site-packages/kubevirt/api_client.py", line 631, in __deserialize_model
    instance = klass(**kwargs)     
  File "/usr/lib/python2.7/site-packages/kubevirt/models/resource_quantity.py", line 57, in __init__
    self.format = format
  File "/usr/lib/python2.7/site-packages/kubevirt/models/resource_quantity.py", line 81, in format
    raise ValueError("Invalid value for `format`, must not be `None`")
ValueError: Invalid value for `format`, must not be `None`
```

**Comment by pkliczewski** [comment] 2018-06-29 11:08
cc @lukas-bednar

**Comment by pkliczewski** [comment] 2018-06-29 13:22
I am using kubevirt `v0.7.0-alpha.4`.

**Comment by lukas-bednar** [comment] 2018-06-29 14:33
I am trying to reproduce your issue, and I am hitting different issue
```
In [2]: a.list_virtual_machine_instance_for_all_namespaces()
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-33de18a05311> in <module>()
----> 1 a.list_virtual_machine_instance_for_all_namespaces()

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/apis/default_api.py in list_virtual_machine_instance_for_all_namespaces(self, **kwargs)
   2882             return self.list_virtual_machine_instance_for_all_namespaces_with_http_info(**kwargs)
   2883         else:
-> 2884             (data) = self.list_virtual_machine_instance_for_all_namespaces_with_http_info(**kwargs)
   2885             return data
   2886 

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/apis/default_api.py in list_virtual_machine_instance_for_all_namespaces_with_http_info(self, **kwargs)
   2976                                         _preload_content=params.get('_preload_content', True),
   2977                                         _request_timeout=params.get('_request_timeout'),
-> 2978                                         collection_formats=collection_formats)
   2979 
   2980     def list_virtual_machine_instance_preset_for_all_namespaces(self, **kwargs):

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    324                                    body, post_params, files,
    325                                    response_type, auth_settings, callback,
--> 326                                    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    327         else:
    328             thread = threading.Thread(target=self.__call_api,

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __call_api(self, resource_path, method, path_params, query_params, header_params, body, post_params, files, response_type, auth_settings, callback, _return_http_data_only, collection_formats, _preload_content, _request_timeout)
    159             # deserialize response data
    160             if response_type:
--> 161                 return_data = self.deserialize(response_data, response_type)
    162             else:
    163                 return_data = None

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in deserialize(self, response, response_type)
    237             data = response.data
    238 
--> 239         return self.__deserialize(data, response_type)
    240 
    241     def __deserialize(self, data, klass):

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    277             return self.__deserialize_datatime(data)
    278         else:
--> 279             return self.__deserialize_model(data, klass)
    280 
    281     def call_api(self, resource_path, method,

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize_model(self, data, klass)
    627                and isinstance(data, (list, dict)):
    628                 value = data[klass.attribute_map[attr]]
--> 629                 kwargs[attr] = self.__deserialize(value, attr_type)
    630 
    631         instance = klass(**kwargs)

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    255                 sub_kls = re.match('list\[(.*)\]', klass).group(1)
    256                 return [self.__deserialize(sub_data, sub_kls)
--> 257                         for sub_data in data]
    258 
    259             if klass.startswith('dict('):

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in <listcomp>(.0)
    255                 sub_kls = re.match('list\[(.*)\]', klass).group(1)
    256                 return [self.__deserialize(sub_data, sub_kls)
--> 257                         for sub_data in data]
    258 
    259             if klass.startswith('dict('):

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    277             return self.__deserialize_datatime(data)
    278         else:
--> 279             return self.__deserialize_model(data, klass)
    280 
    281     def call_api(self, resource_path, method,

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize_model(self, data, klass)
    627                and isinstance(data, (list, dict)):
    628                 value = data[klass.attribute_map[attr]]
--> 629                 kwargs[attr] = self.__deserialize(value, attr_type)
    630 
    631         instance = klass(**kwargs)

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    277             return self.__deserialize_datatime(data)
    278         else:
--> 279             return self.__deserialize_model(data, klass)
    280 
    281     def call_api(self, resource_path, method,

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize_model(self, data, klass)
    627                and isinstance(data, (list, dict)):
    628                 value = data[klass.attribute_map[attr]]
--> 629                 kwargs[attr] = self.__deserialize(value, attr_type)
    630 
    631         instance = klass(**kwargs)

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    277             return self.__deserialize_datatime(data)
    278         else:
--> 279             return self.__deserialize_model(data, klass)
    280 
    281     def call_api(self, resource_path, method,

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize_model(self, data, klass)
    627                and isinstance(data, (list, dict)):
    628                 value = data[klass.attribute_map[attr]]
--> 629                 kwargs[attr] = self.__deserialize(value, attr_type)
    630 
    631         instance = klass(**kwargs)

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    277             return self.__deserialize_datatime(data)
    278         else:
--> 279             return self.__deserialize_model(data, klass)
    280 
    281     def call_api(self, resource_path, method,

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize_model(self, data, klass)
    627                and isinstance(data, (list, dict)):
    628                 value = data[klass.attribute_map[attr]]
--> 629                 kwargs[attr] = self.__deserialize(value, attr_type)
    630 
    631         instance = klass(**kwargs)

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    255                 sub_kls = re.match('list\[(.*)\]', klass).group(1)
    256                 return [self.__deserialize(sub_data, sub_kls)
--> 257                         for sub_data in data]
    258 
    259             if klass.startswith('dict('):

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in <listcomp>(.0)
    255                 sub_kls = re.match('list\[(.*)\]', klass).group(1)
    256                 return [self.__deserialize(sub_data, sub_kls)
--> 257                         for sub_data in data]
    258 
    259             if klass.startswith('dict('):

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    277             return self.__deserialize_datatime(data)
    278         else:
--> 279             return self.__deserialize_model(data, klass)
    280 
    281     def call_api(self, resource_path, method,

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize_model(self, data, klass)
    627                and isinstance(data, (list, dict)):
    628                 value = data[klass.attribute_map[attr]]
--> 629                 kwargs[attr] = self.__deserialize(value, attr_type)
    630 
    631         instance = klass(**kwargs)

~/work/kubevirt-org/kubevirt-pysdk-sandbox/E3/lib/python3.6/site-packages/kubevirt/api_client.py in __deserialize(self, data, klass)
    266                 klass = self.NATIVE_TYPES_MAPPING[klass]
    267             else:
--> 268                 klass = getattr(models, klass)
    269 
    270         if klass in self.PRIMITIVE_TYPES:

AttributeError: module 'kubevirt.models' has no attribute 'V1InterfaceBridge'
```
Anyway I will continue investigating

**Comment by pkliczewski** [comment] 2018-06-29 14:38
I saw this one as well. I had pulled the latest client and it went away.

**Comment by lukas-bednar** [comment] 2018-06-29 16:22
I can you get over that, I have:
```
OCP v3.10.8
kubevirt 0.7.0-alpha.4
kubevirt-py v0.6.0-251-gf38377a
```

And I am still hitting this issue with InterfaceBrigde ... I tried also 0.7.0-alpha.5 but with the same results ...

**Comment by SchSeba** [comment] 2018-07-02 15:37
I am working on the interfaceBridge for now I have a workaround you can clone my repo to work on the resource_quantity because I also have this problem and cant check if my fix work.
[repo](https://github.com/SchSeba/kubevirt/tree/fix-client-python)

I do some research about the resource_quantity problem 
The problem is on the resource.memory

If you look into the v1_resource_requirments.py file the swagger generate is
```python
 swagger_types = {
        'limits': 'dict(str, ResourceQuantity)',
        'requests': 'dict(str, ResourceQuantity)'
    }
```

But if you take a look in the resource.memory in the kubernetes python sdk
[link](https://github.com/kubernetes-client/python/blob/369366a813964e3d72e91d402c5f471275e7a3e5/kubernetes/client/models/v1_resource_requirements.py)

The request there is different
```python
    swagger_types = {
        'limits': 'dict(str, str)',
        'requests': 'dict(str, str)'
    }
```

I am not sure how we can change this configuration.

**Comment by rmohr** [comment] 2018-07-03 07:06
I see that k8s types have definitions like this:

```golang
// OpenAPIDefinition returns openAPI definition for this type.
func (_ Quantity) OpenAPIDefinition() openapi.OpenAPIDefinition {
	return openapi.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Type:   []string{"string"},
				Format: "",
			},
		},
	}
}
```

Resolving https://github.com/kubevirt/kubevirt/issues/1227 would also solve that.

**Closed** 2018-08-13 15:39 UTC
